### PR TITLE
Upgraded welcome message

### PR DESCRIPTION
**Pull request by Eveneit**
Added some flavor to the message, open for changes. 
---
welcomewarrior
---
Hey, I tried to get the docs right and help a bit on the project :)

I'm actually totally new to javascript, node, npm, yarn and github and just managed to clone from github and get a synced working folder where I could launch the game. 

Let me know if something is wrong.

### CODE REVIEW

**Comment by Eveneit** [comment]
Hey, I tried to get the docs right and help a bit on the project :)

I'm actually totally new to javascript, node, npm, yarn and github and just managed to clone from github and get a synced working folder where I could launch the game. 

Let me know if something is wrong.

**Comment by olistic** [comment]
Hey @Eveneit! Thanks a lot for this, it looks nice! After the changes introduced in #147, I started playing with your design to make it a little more subtle and I arrived to this:

screen shot 2018-05-21 at 17 08 08

If you like it, I prefer that you're the one that makes the change because the original idea was yours. Let me know!

BTW, the text version is "+*+~~~+*$#$*+~~~+*+" padded with "~", everything in dim gray, as in #147.

**Comment by olistic** [comment]
Hello @Eveneit, just checking in to see if you're still interested in working on this.

**Comment by olistic** [comment]
Resolved by #191.

**Pull request closed without merging**
